const products = [
    // AC Parts
    { id: "ac-blower-motor", name: "AC Blower Motor", price: "₹2,300", category: "ac", image:"assets/products/motor.jpg", description: "High-quality replacement blower motor for various AC units. Ensures efficient air circulation." },
    { id: "ac-capacitor", name: "AC Capacitor 45/5 µF", price: "₹380", category: "ac", image: "assets/products/ac-capacitor.jpg", description: "Dual run capacitor for AC compressor and fan motors." },
    { id: "ac-copper-kit", name: "AC Copper Installation Kit", price: "₹3,950", category: "ac", image: "assets/products/ac-copper-installation-kit.jpg", description: "Complete kit with copper pipes, insulation, and wiring for split AC installation." },
    { id: "ac-air-filter", name: "AC Air Filter Set", price: "₹450", category: "ac", image: "assets/products/ac-air-filter-set.jpg", description: "Set of high-density filters to ensure clean air and protect the AC unit." },
    { id: "ac-remote", name: "AC Remote Control", price: "₹350", category: "ac", image: "assets/products/ac-remote-control.jpg", description: "Universal remote control compatible with most major AC brands." },
    { id: "ac-condenser-motor", name: "AC Condenser Fan Motor", price: "₹1,950", category: "ac", image: "assets/products/ac-condencor.jpg", description: "Durable fan motor for the outdoor condenser unit." },
    { id: "ac-expansion-valve", name: "AC Expansion Valve", price: "₹1,250", category: "ac", image: "assets/products/ac-expansion-valve.jpg", description: "Regulates refrigerant flow into the evaporator." },
    { id: "ac-pcb", name: "AC PCB Control Board", price: "₹4,600", category: "ac", image: "assets/products/ac-pcb.jpg", description: "Main circuit board for controlling all functions of the air conditioner." },
    { id: "ac-drain-pipe", name: "AC Drain Pipe (5m)", price: "₹260", category: "ac", image: "assets/products/ac-drain-pipe.jpg", description: "Flexible 5-meter pipe for condensate water drainage." },
    { id: "ac-compressor-mount", name: "AC Compressor Mount Kit", price: "₹520", category: "ac", image: "assets/products/ac-copper-installation-kit.jpg", description: "Rubber and metal mounts to reduce compressor vibration and noise." },
    { id: "ac-thermistor", name: "AC Thermistor Sensor", price: "₹320", category: "ac", image: "assets/products/ac-thermistor-sensor.jpg", description: "Temperature sensor for accurate room climate control." },
    { id: "ac-fan-blade", name: "AC Outdoor Unit Fan Blade", price: "₹740", category: "ac", image: "assets/products/ac-outdoor-unit.jpg", description: "Replacement fan blade for the outdoor condenser unit." },

    // Refrigerator Parts
    { id: "fridge-defrost-timer", name: "Refrigerator Defrost Timer", price: "₹1,250", category: "refrigerator", image:"assets/products/defrost.jpg", description: "Controls the defrost cycle in frost-free refrigerators." },
    { id: "fridge-door-gasket", name: "Door Gasket (Universal)", price: "₹990", category: "refrigerator", image: "assets/products/door-gasket-universal.jpg", description: "Universal door seal to maintain internal temperature and efficiency." },
    { id: "thermostat-control", name: "Thermostat Control", price: "₹780", category: "refrigerator", image: "assets/products/thermostat-control.jpg", description: "Thermostat control for temperature regulation." },
    { id: "evaporator-fan-motor", name: "Evaporator Fan Motor", price: "₹1,550", category: "refrigerator", image:"assets/products/motor.jpg", description: "Fan motor for refrigerator evaporator." },
    { id: "starter-relay", name: "Starter Relay", price: "₹430", category: "refrigerator", image: "assets/products/starter-relay.jpg", description: "Relay for compressor start-up." },
    { id: "defrost-heater", name: "Defrost Heater", price: "₹860", category: "refrigerator", image:"assets/products/defrost.jpg", description: "Heater for defrosting refrigerator coils." },
    { id: "refrigerator-pcb", name: "Refrigerator PCB", price: "₹3,950", category: "refrigerator", image: "assets/products/refrigerator-pcb.jpg", description: "Main control board for refrigerator." },
    { id: "water-inlet-valve", name: "Water Inlet Valve", price: "₹1,150", category: "refrigerator", image: "assets/products/water-inlet-valve.jpg", description: "Valve controlling water inlet." },
    { id: "compressor-overload-protector", name: "Compressor Overload Protector", price: "₹540", category: "refrigerator", image: "assets/products/compressor-overload-protector.jpg", description: "Protector for compressor overload." },
    { id: "refrigerator-shelf", name: "Refrigerator Shelf (Glass)", price: "₹1,350", category: "refrigerator", image: "assets/products/refrigerator-shelf.jpg", description: "Glass shelf for refrigerator." },
    { id: "freezer-door-handle", name: "Freezer Door Handle", price: "₹620", category: "refrigerator", image: "assets/products/freezer-door-handle.jpg", description: "Handle for freezer door." },
    { id: "crisper-box", name: "Crisper Box", price: "₹1,200", category: "refrigerator", image: "assets/products/crisper-box.jpg", description: "Crisper box for vegetables." },

    // Washing Machine Parts
    { id: "inlet-valve", name: "Inlet Valve", price: "₹850", category: "washing", image: "assets/products/inlet-valve.jpg", description: "Water inlet valve for washing machine." },
    { id: "drain-pump", name: "Drain Pump", price: "₹1,450", category: "washing", image: "assets/products/drain-pump1.jpg", description: "Pump for draining water." },
    { id: "carbon-brushes", name: "Carbon Brushes", price: "₹420", category: "washing", image:"assets/products/carbon.jpg", description: "Carbon brushes for motor." },
    { id: "drive-belt", name: "Drive Belt", price: "₹320", category: "washing", image: "assets/products/drive-belt.jpg", description: "Drive belt for motor." },
    { id: "door-lock-switch", name: "Door Lock Switch", price: "₹690", category: "washing", image: "assets/products/door-lock-switch.jpg", description: "Switch for door lock." },
    { id: "drain-hose", name: "Drain Hose (2m)", price: "₹210", category: "washing", image: "assets/products/drain-hose.jpg", description: "Drain hose for water." },
    { id: "pressure-switch", name: "Pressure Switch", price: "₹570", category: "washing", image: "assets/products/pressure-switch.jpg", description: "Pressure switch for water level." },
    { id: "shock-absorber-set", name: "Shock Absorber Set", price: "₹1,250", category: "washing", image: "assets/products/shock-absorber-set.jpg", description: "Set of shock absorbers." },
    { id: "motor-coupling", name: "Motor Coupling", price: "₹480", category: "washing", image:"assets/products/motor.jpg", description: "Coupling for motor." },
    { id: "detergent-drawer", name: "Detergent Drawer", price: "₹350", category: "washing", image:"assets/products/Detergent Drawer.jpg", description: "Drawer for detergent." },
    { id: "washer-pcb", name: "Washer PCB", price: "₹3,250", category: "washing", image: "assets/products/washer-pcb.jpg", description: "Control board for washer." },
    { id: "door-seal-gasket", name: "Door Seal Gasket", price: "₹1,150", category: "washing", image: "assets/products/door-gasket-universal.jpg", description: "Seal gasket for door." },

    // Television Parts
    { id: "led-tv-backlight-strips", name: "LED TV Backlight Strips", price: "₹1,800", category: "tv", image: "assets/products/led-tv-backlight-strip.jpg", description: "Backlight strips for LED TV." },
    { id: "led-tv-main-board", name: "LED TV Main Board", price: "₹4,800", category: "tv", image: "assets/products/led-tv-main-board.jpg", description: "Main board for LED TV." },
    { id: "power-supply-board", name: "Power Supply Board", price: "₹2,700", category: "tv", image: "assets/products/power-supply-board.jpg", description: "Power supply board for TV." },
    { id: "t-con-board", name: "T-Con Board", price: "₹2,150", category: "tv", image: "assets/products/t-con-board.jpg", description: "Timing control board." },
    { id: "ir-sensor-board", name: "IR Sensor Board", price: "₹420", category: "tv", image: "assets/products/ir-sensor.jpg", description: "Infrared sensor board." },
    { id: "tv-speakers-pair", name: "TV Speakers Pair", price: "₹650", category: "tv", image: "assets/products/tv-speakers.jpg", description: "Pair of TV speakers." },
    { id: "wifi-module", name: "WiFi Module", price: "₹780", category: "tv", image: "assets/products/wifi-module.jpg", description: "WiFi module for smart TV." },
    { id: "led-strip-diffuser-set", name: "LED Strip Diffuser Set", price: "₹550", category: "tv", image: "assets/products/led-strip.jpg", description: "Diffuser set for LED strips." },
    { id: "remote-control", name: "Remote Control", price: "₹390", category: "tv", image: "assets/products/remote-control.jpg", description: "Remote control for TV." },
    { id: "lvds-cable", name: "LVDS Cable", price: "₹260", category: "tv", image: "assets/products/lvds-cable.jpg", description: "LVDS cable for display." },
    { id: "stand-base-set", name: "Stand Base Set", price: "₹1,050", category: "tv", image: "assets/products/stand-base-set.jpg", description: "Stand base for TV." },
    { id: "panel-buffer-board", name: "Panel Buffer Board", price: "₹1,250", category: "tv", image: "assets/products/panel-buffer-board.jpg", description: "Buffer board for panel." },

    // Cooler Parts
    { id: "cooler-water-pump", name: "Cooler Water Pump", price: "₹520", category: "cooler", image: "assets/products/cooler-water-pump.jpg", description: "Water pump for cooler." },
    { id: "honeycomb-cooling-pad", name: "Honeycomb Cooling Pad", price: "₹780", category: "cooler", image: "assets/products/honeycomb-cooling.jpg", description: "Cooling pad for air cooler." },
    { id: "cooler-motor", name: "Cooler Motor", price: "₹1,350", category: "cooler", image:"assets/products/motor.jpg", description: "Motor for cooler." },
    { id: "float-valve", name: "Float Valve", price: "₹260", category: "cooler", image: "assets/products/float-valve.jpg", description: "Float valve for water tank." },
    { id: "fan-blade", name: "Fan Blade", price: "₹480", category: "cooler", image: "assets/products/fan-blade.jpg", description: "Fan blade for cooler." },
    { id: "water-distribution-pipe", name: "Water Distribution Pipe", price: "₹190", category: "cooler", image: "assets/products/water-distribution.jpg", description: "Pipe for water distribution." },
    { id: "speed-regulator", name: "Speed Regulator", price: "₹340", category: "cooler", image: "assets/products/speed-regulator.jpg", description: "Speed regulator for fan." },
    { id: "castor-wheel-set", name: "Castor Wheel Set", price: "₹420", category: "cooler", image: "assets/products/castor-wheel-set.jpg", description: "Set of castor wheels." },
    { id: "float-switch", name: "Float Switch", price: "₹290", category: "cooler", image: "assets/products/float-switch.jpg", description: "Float switch for water level." },
    { id: "water-level-indicator", name: "Water Level Indicator", price: "₹230", category: "cooler", image: "assets/products/water-level-indicator.jpg", description: "Indicator for water level." },
    { id: "cooler-pcb", name: "Cooler PCB", price: "₹1,250", category: "cooler", image: "assets/products/cooler-pcb.jpg", description: "Control board for cooler." },
    { id: "cooler-remote-control", name: "Remote Control", price: "₹350", category: "cooler", image: "assets/products/remote-control-for-cooler.jpg", description: "Remote control for cooler." },

    // Heater Parts
    { id: "room-heater-coil", name: "Room Heater Coil", price: "₹260", category: "heater", image: "assets/products/room-heater-coil.jpg", description: "Coil for room heater." },
    { id: "ptc-heating-element", name: "PTC Heating Element", price: "₹650", category: "heater", image: "assets/products/ptc-heating-element.jpg", description: "PTC heating element." },
    { id: "heater-fan-motor", name: "Fan Motor", price: "₹820", category: "heater", image:"assets/products/motor.jpg", description: "Fan motor for heater." },
    { id: "tip-over-switch", name: "Tip-Over Switch", price: "₹240", category: "heater", image: "assets/products/Tip-Over Switch.jpg", description: "Safety tip-over switch." },
    { id: "thermostat-knob", name: "Thermostat Knob", price: "₹180", category: "heater", image: "assets/products/thermostat-knob.jpg", description: "Knob for thermostat." },
    { id: "safety-thermal-fuse", name: "Safety Thermal Fuse", price: "₹210", category: "heater", image: "assets/products/safety-thermal-fuse.jpg", description: "Thermal fuse for safety." },
    { id: "power-selector-switch", name: "Power Selector Switch", price: "₹270", category: "heater", image: "assets/products/power-selector-switch.jpg", description: "Switch for power selection." },
    { id: "heater-pcb", name: "Heater PCB", price: "₹1,450", category: "heater", image: "assets/products/heater-pcb.jpg", description: "Control board for heater." },
    { id: "fan-grill", name: "Fan Grill", price: "₹190", category: "heater", image: "assets/products/fan-grill.jpg", description: "Grill for fan." },
    { id: "power-cord", name: "Power Cord (3m)", price: "₹220", category: "heater", image: "assets/products/power-cord-(3m).jpg", description: "Power cord for heater." },
    { id: "indicator-neon-lamp", name: "Indicator Neon Lamp", price: "₹90", category: "heater", image: "assets/products/indicator-neon-lamp.jpg", description: "Indicator neon lamp." },
    { id: "heater-reflector", name: "Heater Reflector", price: "₹350", category: "heater", image: "assets/products/heater-reflector.jpg", description: "Reflector for heater." },
];
